### ISSUE TITLE
Release @voila-dashboards/jupyterlab-gridstack

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila-gridstack#72]
An issue to track the different steps for making the next `voila-gridstack` release, which will include the prebuilt `@voila-dashboards/jupyterlab-gridstack` extension.

### TODO

- [x] Bump the version in the `package.json` (could be aligned on the Python version):

https://github.com/voila-dashboards/voila-gridstack/blob/18ddf6ff504a220e1f9aed0cb9128746387e678f/packages/jupyterlab-gridstack/package.json#L3

- [x] Release a new `voila-gridstack` to PyPI
- [x] Publish `@voila-dashboards/jupyterlab-gridstack` to npm

**Comment by jtpio** [comment]
This can be a good time to also bring the Python version to `0.1.0`.

**Comment by jtpio** [comment]
Published to PyPI: https://pypi.org/project/voila-gridstack/0.1.0/

Published to npm: https://www.npmjs.com/package/@voila-dashboards/jupyterlab-gridstack

**Comment by jtpio** [comment]
Published to conda forge: https://anaconda.org/conda-forge/voila-gridstack
